/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-nov.-2025 23:43:07 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE dim_actor
(
	id_actor serial NOT NULL,
	nombre_tipo_actor varchar(60) NOT NULL
)
;

CREATE TABLE dim_area_tematica
(
	id_area serial NOT NULL,
	nombre_area varchar(120) NOT NULL,
	activo boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE dim_demanda_ref
(
	id_demanda_ref serial NOT NULL,
	nombre_demanda varchar(200) NOT NULL,
	descripcion_demanda text NOT NULL
)
;

CREATE TABLE dim_estado_demanda
(
	id_estado_demanda serial NOT NULL,
	nombre_estado_demanda varchar(50) NOT NULL
)
;

CREATE TABLE dim_estado_vigencia
(
	id_estado_vigencia serial NOT NULL,
	nombre_estado_vigencia varchar(50) NOT NULL
)
;

CREATE TABLE dim_geografia
(
	id_geografia serial NOT NULL,
	provincia varchar(60) NOT NULL,
	departamento varchar(60) NOT NULL,
	lon double precision NOT NULL,
	lat double precision NOT NULL
)
;

CREATE TABLE dim_modalidad
(
	id_modalidad serial NOT NULL,
	nombre_modalidad varchar(60) NOT NULL
)
;

CREATE TABLE dim_oferta_ref
(
	id_oferta_ref serial NOT NULL,
	nombre_oferta varchar(200) NOT NULL,
	descripcion_oferta text NOT NULL
)
;

CREATE TABLE dim_sector_productivo
(
	id_sector serial NOT NULL,
	nombre_sector varchar(60) NOT NULL
)
;

CREATE TABLE dim_tiempo
(
	id_mes integer NOT NULL,
	anio smallint NOT NULL,
	mes_num smallint NOT NULL,
	mes_nombre varchar(15) NOT NULL,
	inicio_mes date NOT NULL,
	fin_mes date NOT NULL
)
;

CREATE TABLE dim_tipo_servicio
(
	id_tipo_servicio serial NOT NULL,
	nombre_tipo_servicio varchar(60) NOT NULL
)
;

CREATE TABLE dim_unidad_academica
(
	id_unidad serial NOT NULL,
	nombre_unidad varchar(120) NOT NULL,
	fecha_inicio_vigencia date NOT NULL,
	fecha_fin_vigencia date NULL,
	id_geografia integer NULL
)
;

CREATE TABLE hecho_cobertura
(
	id_hecho_cobertura bigserial NOT NULL,
	vinculo_count smallint NOT NULL   DEFAULT 1,
	id_demanda_ref integer NULL,
	id_oferta_ref integer NULL,
	id_area integer NULL,
	id_actor integer NULL,
	id_tipo_servicio integer NULL,
	id_mes integer NULL,
	id_geografia integer NULL
)
;

CREATE TABLE hecho_demanda
(
	id_hecho_demanda bigserial NOT NULL,
	demanda_count smallint NOT NULL   DEFAULT 1,
	cubierta_flag boolean NOT NULL   DEFAULT false,
	id_actor integer NULL,
	id_sector integer NULL,
	id_area integer NULL,
	id_tipo_servicio integer NULL,
	id_geografia integer NULL,
	id_estado_demanda integer NULL,
	id_mes integer NULL,
	id_demanda_ref integer NULL
)
;

CREATE TABLE hecho_oferta
(
	id_hecho_oferta bigserial NOT NULL,
	oferta_count smallint NOT NULL   DEFAULT 1,
	vigente_flag boolean NOT NULL   DEFAULT true,
	id_actor integer NOT NULL,
	id_sector integer NOT NULL,
	id_area integer NOT NULL,
	id_tipo_servicio integer NOT NULL,
	id_unidad integer NOT NULL,
	id_modalidad integer NOT NULL,
	id_estado_vigencia integer NOT NULL,
	id_mes_inicio integer NOT NULL,
	id_mes_fin integer NOT NULL,
	id_oferta_ref integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE dim_actor ADD CONSTRAINT PK_dim_actor
	PRIMARY KEY (id_actor)
;

ALTER TABLE dim_actor ADD CONSTRAINT uq_actor UNIQUE (nombre_tipo_actor)
;

ALTER TABLE dim_area_tematica ADD CONSTRAINT PK_dim_area_tematica
	PRIMARY KEY (id_area)
;

ALTER TABLE dim_area_tematica ADD CONSTRAINT uq_area_tematica UNIQUE (nombre_area)
;

ALTER TABLE dim_demanda_ref ADD CONSTRAINT PK_dim_demanda_ref
	PRIMARY KEY (id_demanda_ref)
;

ALTER TABLE dim_demanda_ref ADD CONSTRAINT uq_nombre_demanda UNIQUE (nombre_demanda)
;

ALTER TABLE dim_estado_demanda ADD CONSTRAINT PK_dim_estado_demanda
	PRIMARY KEY (id_estado_demanda)
;

ALTER TABLE dim_estado_demanda ADD CONSTRAINT uq_estado_demanda UNIQUE (nombre_estado_demanda)
;

ALTER TABLE dim_estado_vigencia ADD CONSTRAINT PK_dim_estado_vigencia
	PRIMARY KEY (id_estado_vigencia)
;

ALTER TABLE dim_estado_vigencia ADD CONSTRAINT uq_estado_vigencia UNIQUE (nombre_estado_vigencia)
;

ALTER TABLE dim_geografia ADD CONSTRAINT PK_dim_geografia
	PRIMARY KEY (id_geografia)
;

ALTER TABLE dim_geografia ADD CONSTRAINT uq_prov_loc UNIQUE (provincia,departamento)
;

ALTER TABLE dim_modalidad ADD CONSTRAINT PK_dim_modalidad
	PRIMARY KEY (id_modalidad)
;

ALTER TABLE dim_modalidad ADD CONSTRAINT uq_modalidad UNIQUE (nombre_modalidad)
;

ALTER TABLE dim_oferta_ref ADD CONSTRAINT PK_dim_oferta_ref
	PRIMARY KEY (id_oferta_ref)
;

ALTER TABLE dim_oferta_ref ADD CONSTRAINT uq_nombre_oferta UNIQUE (nombre_oferta)
;

ALTER TABLE dim_sector_productivo ADD CONSTRAINT PK_dim_sector_productivo
	PRIMARY KEY (id_sector)
;

ALTER TABLE dim_sector_productivo ADD CONSTRAINT uq_sector_productivo UNIQUE (nombre_sector)
;

ALTER TABLE dim_tiempo ADD CONSTRAINT PK_dim_tiempo
	PRIMARY KEY (id_mes)
;

ALTER TABLE dim_tiempo ADD CONSTRAINT uq_anio_mes UNIQUE (anio,mes_num)
;

ALTER TABLE dim_tiempo ADD CONSTRAINT check_min_max CHECK (mes_num BETWEEN 1 AND 12)
;

ALTER TABLE dim_tipo_servicio ADD CONSTRAINT PK_dim_tipo_servicio
	PRIMARY KEY (id_tipo_servicio)
;

ALTER TABLE dim_tipo_servicio ADD CONSTRAINT uq__tipo_servicio UNIQUE (nombre_tipo_servicio)
;

ALTER TABLE dim_unidad_academica ADD CONSTRAINT PK_dim_unidad_academica
	PRIMARY KEY (id_unidad)
;

ALTER TABLE dim_unidad_academica ADD CONSTRAINT uq_unidad UNIQUE (nombre_unidad)
;

ALTER TABLE dim_unidad_academica ADD CONSTRAINT check_vigencia CHECK ((fecha_fin_vigencia IS NULL OR fecha_inicio_vigencia <= fecha_fin_vigencia)

)
;

CREATE INDEX IXFK_dim_unidad_academica_dim_geografia ON dim_unidad_academica (id_geografia ASC)
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT PK_hecho_cobertura
	PRIMARY KEY (id_hecho_cobertura)
;

CREATE INDEX IXFK_hecho_cobertura_dim_actor ON hecho_cobertura (id_actor ASC)
;

CREATE INDEX IXFK_hecho_cobertura_dim_area_tematica ON hecho_cobertura (id_area ASC)
;

CREATE INDEX IXFK_hecho_cobertura_dim_demanda_ref ON hecho_cobertura (id_demanda_ref ASC)
;

CREATE INDEX IXFK_hecho_cobertura_dim_geografia ON hecho_cobertura (id_geografia ASC)
;

CREATE INDEX IXFK_hecho_cobertura_dim_mes ON hecho_cobertura (id_mes ASC)
;

CREATE INDEX IXFK_hecho_cobertura_dim_oferta_ref ON hecho_cobertura (id_oferta_ref ASC)
;

CREATE INDEX IXFK_hecho_cobertura_dim_tipo_servicio ON hecho_cobertura (id_tipo_servicio ASC)
;

ALTER TABLE hecho_demanda ADD CONSTRAINT PK_hecho_demanda
	PRIMARY KEY (id_hecho_demanda)
;

ALTER TABLE hecho_demanda ADD CONSTRAINT check_count CHECK ((demanda_count > 0))
;

CREATE INDEX IXFK_hecho_demanda_dim_actor ON hecho_demanda (id_actor ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_area_tematica ON hecho_demanda (id_area ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_demanda_ref ON hecho_demanda (id_demanda_ref ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_estado_demanda ON hecho_demanda (id_estado_demanda ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_geografia ON hecho_demanda (id_geografia ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_mes ON hecho_demanda (id_mes ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_sector_productivo ON hecho_demanda (id_sector ASC)
;

CREATE INDEX IXFK_hecho_demanda_dim_tipo_servicio ON hecho_demanda (id_tipo_servicio ASC)
;

ALTER TABLE hecho_oferta ADD CONSTRAINT PK_hecho_oferta
	PRIMARY KEY (id_hecho_oferta)
;

ALTER TABLE hecho_oferta ADD CONSTRAINT check_oferta_count CHECK (oferta_count > 0)
;

CREATE INDEX IXFK_hecho_oferta_dim_actor ON hecho_oferta (id_actor ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_area_tematica ON hecho_oferta (id_area ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_estado_vigencia ON hecho_oferta (id_estado_vigencia ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_mes ON hecho_oferta (id_mes_inicio ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_mes_03 ON hecho_oferta (id_mes_fin ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_modalidad ON hecho_oferta (id_modalidad ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_oferta_ref ON hecho_oferta (id_oferta_ref ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_sector_productivo ON hecho_oferta (id_sector ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_tipo_servicio ON hecho_oferta (id_tipo_servicio ASC)
;

CREATE INDEX IXFK_hecho_oferta_dim_unidad_academica ON hecho_oferta (id_unidad ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE dim_unidad_academica ADD CONSTRAINT FK_dim_geografia
	FOREIGN KEY (id_geografia) REFERENCES dim_geografia (id_geografia) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_demanda_ref
	FOREIGN KEY (id_demanda_ref) REFERENCES dim_demanda_ref (id_demanda_ref) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_dim_actor
	FOREIGN KEY (id_actor) REFERENCES dim_actor (id_actor) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_dim_area_tematica
	FOREIGN KEY (id_area) REFERENCES dim_area_tematica (id_area) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_dim_geografia
	FOREIGN KEY (id_geografia) REFERENCES dim_geografia (id_geografia) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_dim_mes
	FOREIGN KEY (id_mes) REFERENCES dim_tiempo (id_mes) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_dim_tipo_servicio
	FOREIGN KEY (id_tipo_servicio) REFERENCES dim_tipo_servicio (id_tipo_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_cobertura ADD CONSTRAINT FK_oferta_ref
	FOREIGN KEY (id_oferta_ref) REFERENCES dim_oferta_ref (id_oferta_ref) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_actor
	FOREIGN KEY (id_actor) REFERENCES dim_actor (id_actor) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_area_tematica
	FOREIGN KEY (id_area) REFERENCES dim_area_tematica (id_area) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_demanda_ref
	FOREIGN KEY (id_demanda_ref) REFERENCES dim_demanda_ref (id_demanda_ref) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_estado_demanda
	FOREIGN KEY (id_estado_demanda) REFERENCES dim_estado_demanda (id_estado_demanda) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_geografia
	FOREIGN KEY (id_geografia) REFERENCES dim_geografia (id_geografia) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_mes_registro
	FOREIGN KEY (id_mes) REFERENCES dim_tiempo (id_mes) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_sector_productivo
	FOREIGN KEY (id_sector) REFERENCES dim_sector_productivo (id_sector) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_demanda ADD CONSTRAINT FK_dim_tipo_servicio
	FOREIGN KEY (id_tipo_servicio) REFERENCES dim_tipo_servicio (id_tipo_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_area_tematica
	FOREIGN KEY (id_area) REFERENCES dim_area_tematica (id_area) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_dim_actor
	FOREIGN KEY (id_actor) REFERENCES dim_actor (id_actor) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_dim_mes_fin
	FOREIGN KEY (id_mes_fin) REFERENCES dim_tiempo (id_mes) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_dim_mes_inicio
	FOREIGN KEY (id_mes_inicio) REFERENCES dim_tiempo (id_mes) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_dim_oferta_ref
	FOREIGN KEY (id_oferta_ref) REFERENCES dim_oferta_ref (id_oferta_ref) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_dim_sector_productivo
	FOREIGN KEY (id_sector) REFERENCES dim_sector_productivo (id_sector) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_estado_vigencia
	FOREIGN KEY (id_estado_vigencia) REFERENCES dim_estado_vigencia (id_estado_vigencia) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_hecho_oferta_dim_modalidad
	FOREIGN KEY (id_modalidad) REFERENCES dim_modalidad (id_modalidad) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_tipo_servicio
	FOREIGN KEY (id_tipo_servicio) REFERENCES dim_tipo_servicio (id_tipo_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE hecho_oferta ADD CONSTRAINT FK_unidad_academica
	FOREIGN KEY (id_unidad) REFERENCES dim_unidad_academica (id_unidad) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

COMMENT ON CONSTRAINT uq_prov_loc ON dim_geografia IS 'Evita duplicación de combinación provincia-localidad.'
;

 

 

 

 

 

 

 

 

 
